name: example_app
description: Example Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  追加パッケージ
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^2.0.1
  json_annotation: ^4.5.0
  audioplayers: ^0.20.1
  shared_preferences: ^2.0.15
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 開発用パッケージ
  flutter_lints: ^1.0.0
  pedantic_mono: any
  build_runner: ^2.1.10
  freezed: ^2.0.2
  json_serializable: ^6.2.0
  golden_toolkit: ^0.9.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/sounds/
